### PR TITLE
Move px-component generator to hybrid element structure.

### PR DESCRIPTION
**Pull request by mdwragg**
Moves us to a hybrid element structure.

### CODE REVIEW

**Comment by mdwragg** [comment]
@davidrleonard @benoitjchevalier - can you take a gander at this please? Thanks.

**Comment by mdwragg** [comment]
(p.s. hold off merging until we sort the hydrolysis issue...)

**Comment by mdwragg** [comment]
True about the counter. But replace it with what?

**Comment by runn-vermel** [comment]
My money is on replacing it with nothing. That means there's nothing to delete when you start your project. We don't need sample code that we just delete every time. starting with a clean slate is good.

**Comment by benoitjchevalier** [comment]
I guess it depends if we want to make this just an empty component easy for us to use or something a bit more "teaching" where we could include a couple of props and lifecycle callbacks for example

**Comment by mdwragg** [comment]
Problem with empty is that most of the content is about templated places where the name of the component goes and how to drive the demo page stuff (which is like a swiss watch, if I didn't have a working (simple) example to refer to I'd never be able to get it working...)

Regardless, let's treat that question as something different than the original intent of this PR.

**Pull request merged**
